name: Comment Branch Name on Issues

on:
    issues:
        types: [opened]

permissions:
    issues: write

jobs:
    comment-branch-name:
        runs-on: ubuntu-latest
        steps:
            - name: Comment Branch Name
              uses: SEKI-YUTA/action-comment-working-branch-name@v1.0.0
              with:
                  app-name: "Your App Name"
